import { capabilityIds, type CapabilityFit, type CapabilityId, type Concept } from "./types";

const baseFit: Record<CapabilityId, CapabilityFit> = {
  nextAction: "New UI only",
  readiness: "Adapted",
  templateStart: "Adapted",
  activeLogging: "Adapted",
  setRoles: "Reused",
  restTimer: "Adapted",
  prescriptions: "Reused",
  safetySubstitution: "Adapted",
  overrides: "Adapted",
  submission: "Reused",
  summary: "Adapted",
  templates: "Adapted",
  mesocyclePlanning: "Adapted",
  progressOverview: "Adapted",
  liftAnalysis: "Adapted",
  historyEditing: "Adapted",
  settings: "Adapted",
  privacy: "Reused",
  importExport: "Reused",
  syncConsent: "Reused",
  offlineUpdates: "Reused",
  conflictRecovery: "Reused",
};

function fit(overrides: Partial<Record<CapabilityId, CapabilityFit>> = {}) {
  return Object.fromEntries(
    capabilityIds.map((id) => [id, overrides[id] ?? baseFit[id]]),
  ) as Record<CapabilityId, CapabilityFit>;
}

export const concepts: Concept[] = [
  {
    id: "dual-track",
    rank: 1,
    name: "Dual Track",
    thesis: "A live session sequencer keeps the workout map visible while a stable control dock handles the current set.",
    aesthetic: "Precision audio workstation: dark tracks, quiet grid lines, bright playhead, compact numeric type.",
    font: "Space Grotesk",
    responsive: "Phone uses stacked lanes over a thumb dock; tablet and desktop widen the lanes and add analysis alongside the same playhead.",
    layout: "tracks",
    dimensions: {
      metaphor: "music sequencer",
      navigation: "mode rail plus playhead",
      primaryUnit: "exercise lane",
      workoutModel: "parallel lanes with control dock",
      planningModel: "week arrangement board",
      progressModel: "overlaid performance tracks",
      interactionGrammar: "scrub, tap, arm, commit",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 16, platformFit: 12, safetyRisk: 8 },
      experience: { gymSpeed: 24, screenEconomy: 19, clarity: 18, aesthetics: 14, accessibility: 7, scalability: 9 },
    },
    capabilityFit: fit({ nextAction: "Adapted", progressOverview: "New UI only", liftAnalysis: "New UI only" }),
    theme: { canvas: "#0D1117", surface: "#151B23", ink: "#F2F6FA", muted: "#9CA8B5", accent: "#39D98A" },
    strengths: ["Fast one-handed logging", "Persistent session context", "Data model maps naturally to lanes", "Distinct planning and analysis language"],
    risks: ["Horizontal track density needs strict 320 px behavior", "Playhead and lane semantics require careful screen-reader alternatives"],
  },
  {
    id: "bento-studio",
    rank: 2,
    name: "Bento Studio",
    thesis: "An adaptive tile field changes composition by task instead of forcing every workflow through a fixed navigation template.",
    aesthetic: "Soft geometric studio: crisp white modules, large negative space, precise blue signals, varied tile proportions.",
    font: "Manrope",
    responsive: "Tiles collapse into an ordered phone feed and expand into a masonry workspace without changing their priority semantics.",
    layout: "bento",
    dimensions: {
      metaphor: "adaptive studio",
      navigation: "contextual tile launcher",
      primaryUnit: "task module",
      workoutModel: "priority tile plus set strip",
      planningModel: "modular planning canvas",
      progressModel: "resizable insight modules",
      interactionGrammar: "open, pin, expand, resolve",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 18, platformFit: 14, safetyRisk: 10 },
      experience: { gymSpeed: 22, screenEconomy: 18, clarity: 17, aesthetics: 13, accessibility: 8, scalability: 7 },
    },
    capabilityFit: fit({ nextAction: "New UI only", progressOverview: "New UI only" }),
    theme: { canvas: "#F2F7FB", surface: "#FFFFFF", ink: "#15243A", muted: "#617189", accent: "#2B7FFF" },
    strengths: ["Highest backend feasibility", "Excellent responsive composition", "Complex planning can expand without dominating Today"],
    risks: ["Can become a generic dashboard if tile priority is not rigorously task-driven", "Customization is intentionally out of scope"],
  },
  {
    id: "set-stack",
    rank: 3,
    name: "Set Stack",
    thesis: "The active set is the entire foreground; a compact deck and exercise rail preserve context without competing for attention.",
    aesthetic: "Tactile black cards with fluorescent edges, oversized set numbers, and restrained depth.",
    font: "DM Sans",
    responsive: "Phone shows one primary card; larger screens fan upcoming cards and expose the full exercise rail.",
    layout: "stack",
    dimensions: {
      metaphor: "card deck",
      navigation: "stack plus exercise rail",
      primaryUnit: "current set card",
      workoutModel: "single-set focus stack",
      planningModel: "sortable session decks",
      progressModel: "before-and-after card stories",
      interactionGrammar: "advance, defer, inspect, undo",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 17, platformFit: 12, safetyRisk: 8 },
      experience: { gymSpeed: 25, screenEconomy: 20, clarity: 17, aesthetics: 14, accessibility: 6, scalability: 6 },
    },
    capabilityFit: fit({ nextAction: "Adapted", activeLogging: "New UI only", historyEditing: "New UI only" }),
    theme: { canvas: "#0B0C10", surface: "#181B22", ink: "#F5F7FA", muted: "#A6ADBA", accent: "#C8FF3D" },
    strengths: ["Best raw in-gym speed", "Extreme screen economy", "Clear interruption recovery", "Memorable interaction identity"],
    risks: ["Hidden future sets can weaken program awareness", "Gestures require fully equivalent visible controls"],
  },
  {
    id: "weekline",
    rank: 4,
    name: "Weekline",
    thesis: "Everything is anchored to a continuous training week, making today, recovery, upcoming work, and history one temporal system.",
    aesthetic: "Calm calendar editorial with a violet time spine, compact event bands, and measured whitespace.",
    font: "Source Sans 3",
    responsive: "Phone uses a vertical time spine; wider screens unfold the same model into horizontal days and adjacent detail.",
    layout: "timeline",
    dimensions: {
      metaphor: "weekly timeline",
      navigation: "temporal scrubber",
      primaryUnit: "time event",
      workoutModel: "session event expanded in place",
      planningModel: "week scheduling rail",
      progressModel: "longitudinal trend timeline",
      interactionGrammar: "scrub, expand, reschedule, compare",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 17, platformFit: 13, safetyRisk: 8 },
      experience: { gymSpeed: 22, screenEconomy: 17, clarity: 18, aesthetics: 13, accessibility: 8, scalability: 8 },
    },
    capabilityFit: fit({ nextAction: "New UI only", mesocyclePlanning: "New UI only", progressOverview: "New UI only" }),
    theme: { canvas: "#F4F0FF", surface: "#FFFFFF", ink: "#241A3A", muted: "#6A5B7B", accent: "#6F4EF2" },
    strengths: ["Best mental model for training continuity", "Strong readiness-to-plan relationship", "Maps cleanly to dated local records"],
    risks: ["Long workouts can overwhelm the timeline", "Undated settings and data tasks need a secondary utility layer"],
  },
  {
    id: "mission-console",
    rank: 5,
    name: "Mission Console",
    thesis: "Readiness is a preflight check, the workout is a staged mission, and submission becomes an explicit debrief.",
    aesthetic: "Deep technical console with luminous telemetry, sectional dividers, and disciplined system labels.",
    font: "IBM Plex Sans",
    responsive: "Phone runs a single mission stage at a time; desktop becomes a multi-panel telemetry console.",
    layout: "console",
    dimensions: {
      metaphor: "mission control",
      navigation: "stage gate sequence",
      primaryUnit: "mission stage",
      workoutModel: "preflight-execute-debrief",
      planningModel: "mission manifest",
      progressModel: "telemetry archive",
      interactionGrammar: "check, arm, execute, debrief",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 15, platformFit: 12, safetyRisk: 8 },
      experience: { gymSpeed: 22, screenEconomy: 16, clarity: 17, aesthetics: 14, accessibility: 7, scalability: 8 },
    },
    capabilityFit: fit({ readiness: "New UI only", submission: "Adapted", summary: "New UI only" }),
    theme: { canvas: "#071219", surface: "#0B1E29", ink: "#D8F6FF", muted: "#76A9B8", accent: "#2CF2B4" },
    strengths: ["Excellent readiness and finality framing", "Strong status visibility", "Existing workflow state machine maps well"],
    risks: ["Can feel overdramatic for routine sessions", "Technical density must not imply medical precision"],
  },
  {
    id: "iron-ledger",
    rank: 6,
    name: "Iron Ledger",
    thesis: "A chronological training record behaves like a serious notebook, with current actions embedded directly into the ledger.",
    aesthetic: "Warm paper, graphite rules, tabbed index marks, stamped status, and compact serif-like hierarchy rendered with accessible sans type.",
    font: "IBM Plex Sans",
    responsive: "Phone is a narrow dated page; desktop becomes a two-page spread with index and analysis margins.",
    layout: "ledger",
    dimensions: {
      metaphor: "training notebook",
      navigation: "dated index and section tabs",
      primaryUnit: "ledger entry",
      workoutModel: "editable session record",
      planningModel: "program folio",
      progressModel: "annotated historical ledger",
      interactionGrammar: "write, stamp, annotate, index",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 19, platformFit: 13, safetyRisk: 9 },
      experience: { gymSpeed: 18, screenEconomy: 18, clarity: 17, aesthetics: 12, accessibility: 8, scalability: 6 },
    },
    capabilityFit: fit({ nextAction: "Adapted", historyEditing: "New UI only" }),
    theme: { canvas: "#F3EBD8", surface: "#FFF9EA", ink: "#2A241C", muted: "#746858", accent: "#B5432F" },
    strengths: ["Lowest migration risk", "History and editing feel native", "Dense without card proliferation"],
    risks: ["Workout action priority is less immediate", "Paper metaphor can become decorative instead of functional"],
  },
  {
    id: "stadium-live",
    rank: 7,
    name: "Stadium Live",
    thesis: "The session is a live event: lineup, current attempt, clock, results ticker, and post-game recap.",
    aesthetic: "Broadcast scoreboard, giant numerals, condensed labels, live ticker, warm floodlight contrast.",
    font: "Roboto",
    responsive: "Phone prioritizes the live score and attempt; desktop adds lineup, ticker, and split statistics.",
    layout: "scoreboard",
    dimensions: {
      metaphor: "live broadcast",
      navigation: "lineup and event ticker",
      primaryUnit: "attempt event",
      workoutModel: "live scoreboard",
      planningModel: "team sheet",
      progressModel: "season statistics",
      interactionGrammar: "start event, record attempt, review replay",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 16, platformFit: 11, safetyRisk: 7 },
      experience: { gymSpeed: 23, screenEconomy: 17, clarity: 15, aesthetics: 14, accessibility: 6, scalability: 7 },
    },
    capabilityFit: fit({ activeLogging: "New UI only", summary: "New UI only", progressOverview: "New UI only" }),
    theme: { canvas: "#140B0B", surface: "#241212", ink: "#FFF4E8", muted: "#C5AFA2", accent: "#FF4B24" },
    strengths: ["Highly motivating active state", "PRs and summaries become naturally celebratory", "Clear temporal session phases"],
    risks: ["Broadcast density can distract", "Large-number hierarchy needs careful long-label handling"],
  },
  {
    id: "editorial-performance",
    rank: 8,
    name: "Editorial Performance",
    thesis: "The app becomes a concise training publication: today is the front page, planning is an issue, and progress is a reported story.",
    aesthetic: "High-contrast editorial typography, chapter rules, asymmetric columns, restrained red annotations.",
    font: "DM Sans",
    responsive: "Phone flows as a single article; wider layouts introduce columns without changing reading order.",
    layout: "editorial",
    dimensions: {
      metaphor: "performance magazine",
      navigation: "chapter index",
      primaryUnit: "story section",
      workoutModel: "live field report",
      planningModel: "program issue",
      progressModel: "narrative analysis feature",
      interactionGrammar: "read, reveal, annotate, continue",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 18, platformFit: 12, safetyRisk: 7 },
      experience: { gymSpeed: 17, screenEconomy: 16, clarity: 17, aesthetics: 14, accessibility: 8, scalability: 6 },
    },
    capabilityFit: fit({ summary: "New UI only", progressOverview: "New UI only", liftAnalysis: "New UI only" }),
    theme: { canvas: "#FAF7F0", surface: "#FFFFFF", ink: "#1D1A17", muted: "#77706A", accent: "#D34D3D" },
    strengths: ["Best long-form explanations", "Exceptional progress storytelling", "Strong accessibility reading order"],
    risks: ["Slower during active lifting", "Editorial pacing can consume vertical space"],
  },
  {
    id: "body-atlas",
    rank: 9,
    name: "Body Atlas",
    thesis: "The body is the app map; training need, readiness, volume, upcoming work, and progress radiate from anatomical regions.",
    aesthetic: "Clinical contour illustration, translucent tissue fields, precise labels, calm teal highlights.",
    font: "Source Sans 3",
    responsive: "Phone alternates map and region sheet; larger screens keep the atlas visible beside detailed analysis.",
    layout: "atlas",
    dimensions: {
      metaphor: "anatomical atlas",
      navigation: "body-region map",
      primaryUnit: "muscle region",
      workoutModel: "body map plus active region sheet",
      planningModel: "coverage atlas",
      progressModel: "regional adaptation map",
      interactionGrammar: "locate, select, isolate, compare",
    },
    scores: {
      backend: { domainReuse: 29, stateReuse: 19, adapterEffort: 13, platformFit: 9, safetyRisk: 5 },
      experience: { gymSpeed: 19, screenEconomy: 16, clarity: 17, aesthetics: 15, accessibility: 7, scalability: 8 },
    },
    capabilityFit: fit({ nextAction: "New UI only", mesocyclePlanning: "New UI only", progressOverview: "New UI only", liftAnalysis: "New UI only" }),
    theme: { canvas: "#EAF4F2", surface: "#F9FFFD", ink: "#153F3A", muted: "#486A63", accent: "#006B5D" },
    strengths: ["Existing taxonomy supports the core map", "Exceptional muscle-volume comprehension", "Visually unlike conventional trackers"],
    risks: ["Anatomical geometry and keyboard equivalence are expensive", "Exercise-level logging is less natural than region analysis"],
  },
  {
    id: "coach-thread",
    rank: 10,
    name: "Coach Thread",
    thesis: "A deterministic coaching thread explains each decision and embeds the next safe action directly in sequence.",
    aesthetic: "Calm conversation transcript, generous reading measure, inline control cards, subtle blue authorship markers.",
    font: "Inter",
    responsive: "The chronological thread works unchanged on phone; desktop adds a pinned context rail and evidence inspector.",
    layout: "thread",
    dimensions: {
      metaphor: "coach conversation",
      navigation: "thread anchors and context rail",
      primaryUnit: "coach turn",
      workoutModel: "action cards in transcript",
      planningModel: "guided interview",
      progressModel: "coach review thread",
      interactionGrammar: "answer, choose, explain, confirm",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 12, platformFit: 10, safetyRisk: 6 },
      experience: { gymSpeed: 21, screenEconomy: 18, clarity: 16, aesthetics: 11, accessibility: 8, scalability: 6 },
    },
    capabilityFit: fit({ readiness: "New UI only", mesocyclePlanning: "New UI only", conflictRecovery: "New UI only" }),
    theme: { canvas: "#EEF2F6", surface: "#FFFFFF", ink: "#17212B", muted: "#607080", accent: "#0F6CBD" },
    strengths: ["Excellent explanation and uncertainty handling", "Guided planning feels natural", "No AI dependency required"],
    risks: ["Long transcripts become cumbersome", "Conversation affordances may falsely imply open-ended AI"],
  },
  {
    id: "command-gym",
    rank: 11,
    name: "Command Gym",
    thesis: "Every destination is reachable through a compact command surface backed by context-aware one-tap actions.",
    aesthetic: "Brutalist terminal, phosphor text, strict grids, terse labels, and high-contrast focus states.",
    font: "IBM Plex Sans",
    responsive: "Phone exposes quick command chips over a prompt; desktop expands into a full command palette and results pane.",
    layout: "command",
    dimensions: {
      metaphor: "command terminal",
      navigation: "command palette",
      primaryUnit: "command result",
      workoutModel: "prompt plus numeric console",
      planningModel: "structured command builder",
      progressModel: "query results",
      interactionGrammar: "type, choose, execute, recall",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 14, platformFit: 10, safetyRisk: 6 },
      experience: { gymSpeed: 22, screenEconomy: 20, clarity: 13, aesthetics: 9, accessibility: 5, scalability: 4 },
    },
    capabilityFit: fit({ nextAction: "New UI only", settings: "New UI only", importExport: "Adapted" }),
    theme: { canvas: "#030C05", surface: "#07140A", ink: "#D7FFD5", muted: "#7BB97A", accent: "#62FF7B" },
    strengths: ["Fast expert access", "Exceptional screen economy", "Strong keyboard support"],
    risks: ["Discoverability is weak", "Terminal styling can exclude nontechnical users", "Mobile text entry is costly"],
  },
  {
    id: "training-workshop",
    rank: 12,
    name: "Training Workshop",
    thesis: "Exercises are tools arranged on a bench; programs are trays and adjustments happen through direct manipulation of the work objects.",
    aesthetic: "Tactile hardware, ruled workbench surfaces, inset trays, engraved labels, warm industrial material cues.",
    font: "Roboto",
    responsive: "Phone uses stacked tool trays and a bottom workbench; desktop becomes a spatial bench with side inventory.",
    layout: "workshop",
    dimensions: {
      metaphor: "equipment workshop",
      navigation: "tool trays",
      primaryUnit: "exercise tool",
      workoutModel: "active workbench",
      planningModel: "assemble program trays",
      progressModel: "maintenance and wear log",
      interactionGrammar: "pick up, configure, place, inspect",
    },
    scores: {
      backend: { domainReuse: 30, stateReuse: 20, adapterEffort: 13, platformFit: 8, safetyRisk: 5 },
      experience: { gymSpeed: 19, screenEconomy: 15, clarity: 15, aesthetics: 14, accessibility: 6, scalability: 6 },
    },
    capabilityFit: fit({ templateStart: "New UI only", activeLogging: "New UI only", mesocyclePlanning: "New UI only" }),
    theme: { canvas: "#E7E0D5", surface: "#F8F3EA", ink: "#292A28", muted: "#706D65", accent: "#C4602A" },
    strengths: ["Excellent template and exercise manipulation metaphor", "Highly differentiated", "Strong equipment constraint visualization"],
    risks: ["Direct manipulation is costly to make accessible", "Skeuomorphism can reduce information density"],
  },
  {
    id: "program-circuit",
    rank: 13,
    name: "Program Circuit",
    thesis: "Exercises, muscles, sessions, fatigue, and progression are nodes in an inspectable circuit rather than isolated lists.",
    aesthetic: "Technical schematic, fine orthogonal connectors, labeled nodes, restrained coral signal paths.",
    font: "IBM Plex Sans",
    responsive: "Phone shows one traversable branch plus an outline; desktop exposes the full graph and side inspector.",
    layout: "circuit",
    dimensions: {
      metaphor: "signal circuit",
      navigation: "node graph",
      primaryUnit: "connected node",
      workoutModel: "active path traversal",
      planningModel: "program dependency graph",
      progressModel: "signal-strength network",
      interactionGrammar: "trace, branch, inspect, reroute",
    },
    scores: {
      backend: { domainReuse: 28, stateReuse: 19, adapterEffort: 11, platformFit: 9, safetyRisk: 6 },
      experience: { gymSpeed: 17, screenEconomy: 13, clarity: 15, aesthetics: 14, accessibility: 7, scalability: 10 },
    },
    capabilityFit: fit({ activeLogging: "New UI only", mesocyclePlanning: "New UI only", progressOverview: "New UI only", conflictRecovery: "New UI only" }),
    theme: { canvas: "#EEF3F7", surface: "#FFFFFF", ink: "#13283A", muted: "#5F7384", accent: "#E15544" },
    strengths: ["Best program-systems explanation", "Excellent for mesocycle conflict review", "Scales to evidence provenance"],
    risks: ["Graph navigation is expensive on a phone", "Automated layout and accessible linear equivalents are mandatory"],
  },
  {
    id: "orbit",
    rank: 14,
    name: "Orbit",
    thesis: "The current action occupies the center while readiness, plan, progress, and data orbit as spatially stable satellites.",
    aesthetic: "Dark celestial field, concentric guides, luminous violet arcs, minimal labels, smooth spatial transitions.",
    font: "Space Grotesk",
    responsive: "Phone uses one orbit and a linear fallback list; wider screens reveal nested rings and persistent detail.",
    layout: "orbit",
    dimensions: {
      metaphor: "orbital system",
      navigation: "radial satellites",
      primaryUnit: "orbiting state",
      workoutModel: "center action with set ring",
      planningModel: "nested program orbits",
      progressModel: "concentric completion arcs",
      interactionGrammar: "rotate, center, expand, return",
    },
    scores: {
      backend: { domainReuse: 28, stateReuse: 18, adapterEffort: 10, platformFit: 8, safetyRisk: 6 },
      experience: { gymSpeed: 18, screenEconomy: 18, clarity: 13, aesthetics: 15, accessibility: 5, scalability: 5 },
    },
    capabilityFit: fit({ nextAction: "New UI only", activeLogging: "New UI only", mesocyclePlanning: "New UI only", progressOverview: "New UI only" }),
    theme: { canvas: "#090B1A", surface: "#14182C", ink: "#F3F5FF", muted: "#9EA7CC", accent: "#8E7CFF" },
    strengths: ["Most distinctive spatial identity", "Current action is unmissable", "Elegant high-level status"],
    risks: ["Radial controls waste rectangular screen space", "Accessibility and precise numeric editing are difficult"],
  },
  {
    id: "quest-map",
    rank: 15,
    name: "Quest Map",
    thesis: "A mesocycle becomes a traversable route whose stages reveal workouts, recovery, and evidence-backed milestones.",
    aesthetic: "Illustrated training terrain, route markers, stamped milestones, restrained parchment texture, warm achievement color.",
    font: "Manrope",
    responsive: "Phone follows a vertical route; desktop opens the full terrain with stage details and progress legend.",
    layout: "quest",
    dimensions: {
      metaphor: "training expedition",
      navigation: "journey map",
      primaryUnit: "route stage",
      workoutModel: "stage encounter",
      planningModel: "route construction",
      progressModel: "unlocked journey",
      interactionGrammar: "choose route, enter stage, complete, unlock",
    },
    scores: {
      backend: { domainReuse: 27, stateReuse: 18, adapterEffort: 8, platformFit: 7, safetyRisk: 5 },
      experience: { gymSpeed: 20, screenEconomy: 15, clarity: 14, aesthetics: 15, accessibility: 7, scalability: 6 },
    },
    capabilityFit: fit({ nextAction: "New UI only", mesocyclePlanning: "Requires backend change", progressOverview: "Requires backend change", summary: "New UI only" }),
    theme: { canvas: "#F3E9D2", surface: "#FFF7E3", ink: "#2E3827", muted: "#6D765D", accent: "#D8872D" },
    strengths: ["Strong motivation and mesocycle identity", "Excellent sense of continuity", "Highly memorable"],
    risks: ["Persistent unlock state is not in the current contract", "Gamification can conflict with conservative readiness and deload guidance"],
  },
];

export function backendTotal(concept: Concept) {
  return Object.values(concept.scores.backend).reduce((sum, value) => sum + value, 0);
}

export function experienceTotal(concept: Concept) {
  return Object.values(concept.scores.experience).reduce((sum, value) => sum + value, 0);
}

export function compositeScore(concept: Concept) {
  return Number((experienceTotal(concept) * 0.6 + backendTotal(concept) * 0.4).toFixed(1));
}

export function structuralDifferenceCount(a: Concept, b: Concept) {
  return (Object.keys(a.dimensions) as Array<keyof Concept["dimensions"]>).filter(
    (key) => a.dimensions[key] !== b.dimensions[key],
  ).length;
}
